name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: ${{ github.event.pull_request.commits }} + 1

      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          include_all_old_new_renamed_files: true
          separator: "|"
          old_new_files_separator: "|"
          files: |
            **/*.md
            **/*.MD
            **/*.mmd
            **/*.MMD
            **/*.mermaid
            **/*.MERMAID
      

      - name: Show changed files output
        run: echo '${{ toJSON(steps.changed-files.outputs) }}'
